linters:
  disable:
    - maligned
    - lll
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - nakedret
    - funlen
    - wsl
    - gocognit
    - godox
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - errcheck
