builds:
  - goos:
    - linux
    goarch:
    - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.build={{.Version}}
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
aurs:
  -
    homepage: "https://github.com/cenkalti/container-manager"
    description: "Manager for Docker containers"
    maintainers:
      - 'Cenk Alti <cenkalti@gmail.com>'
    contributors:
      - 'Cenk Alti <cenkalti@gmail.com>'
    license: "MIT"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/container-manager-bin.git'
    # List of files that can contain user-made changes and should be preserved
    backup:
      - /etc/container-manager.yaml
    package: |-
      # bin
      install -Dm755 "./container-manager" "${pkgdir}/usr/bin/container-manager"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/container-manager/LICENSE"
    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
